<?php
/**
 * Product list template
 *
 * @var $block Ecentura\LookBook\Block\Index\LookBook;
 */
$data = $block->getPostCollection();
?>

<div id="image-map">
    <img src=" <?php echo $this->getViewFileUrl('Ecentura_LookBook::image/image.jpeg'); ?>" alt="Our Locations">
    <?php foreach( $data as $key => $value): ?>
    <div class="pin " data-xpos="<?=$value['xpos']  ?>" data-ypos="<?=$value['ypos']  ?>" >
    <h2><?=$value['title']  ?></h2>
    <p><?=$value['description']  ?></p>
    </div>
    <?php endforeach; ?>
</div>

<script type="text/javascript" xml="space">// <![CDATA[
    require(['jquery', ], function ($) {
        $(document).ready(function(){

            var tooltipDirection;
            for (i=0; i<$(".pin").length; i++)
            {
                n = i+1;
                if ($(".pin").eq(i).hasClass('pin-down')) {
                    tooltipDirection = 'tooltip-down';
                } else {
                    tooltipDirection = 'tooltip-up';
                }
                // append the tooltip
                $("#image-map").append("<div style='left:"+$(".pin").eq(i).data('xpos')+"px;top:"+$(".pin").eq(i).data('ypos')+"px' class='" + tooltipDirection+"'> <span class='info'>" + n +"</span>\
                                            <div class='tooltip'>" + $(".pin").eq(i).html() + "</div>\
                                    </div>");
            }
            $('.tooltip-up, .tooltip-down').mouseenter(function(){
                $(this).children('.tooltip').fadeIn(100);
            }).mouseleave(function(){
                $(this).children('.tooltip').fadeOut(100);
            })
        });
    });

</script>

