<?php
/**
 * Product list template
 *
 * @var $block Ecentura\LookBook\Block\Index\LookBook;
 */
$data = $block->getImageLookBook();
$dataLocation = $block->getLocationLookBook($data['location']);
?>

<div id="image-map">
    <img src=" <?= $block->getURlImage($data['image'])?>" alt="Our Locations">
    <?php foreach( $dataLocation as $key => $values): ?>
        <?php foreach( $values as$value ): ?>

            <div class="pin " data-xpos="<?=$value['xpos']  ?>" data-ypos="<?=$value['ypos']  ?>" >
            <h2><?=$value['title']  ?></h2>
            <p><?=$value['description']  ?></p>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>

<script type="text/javascript" xml="space">// <![CDATA[
    require(['jquery', ], function ($) {
        $(document).ready(function(){

            var tooltipDirection;
            for (i=0; i<$(".pin").length; i++)
            {
                n = i+1;
                $("#image-map").append("<div style='left:"+$(".pin").eq(i).data('xpos')+"px;top:"+$(".pin").eq(i).data('ypos')+"px' class='tooltip-up'> <div class='info'> " + n +"</div>\
                                            <div class='tooltip'>" + $(".pin").eq(i).html() + "</div>\
                                    </div>");
            }
            $('.tooltip-up, .tooltip-down').mouseenter(function(){
                $(this).children('.tooltip').fadeIn(100);
            }).mouseleave(function(){
                $(this).children('.tooltip').fadeOut(100);
            })
        });
    });

</script>

