<div class="col-md-9 main-home hidden-xs">
    <div class="panel panel-default main-slide">
        <div class="row height green">
            <div class="col-md-6 main-category">
                <div class="text" data-id="131336"><h2>Katoenen tassen bedrukken</h2>
                    <ul>
                        <li>Al vanaf <strong>10</strong> stuks voor <strong>€ 45<span>,67</span></strong></li>
                        <li>Leverbaar binnen <strong><span class="delivery-days">5</span> werkdagen</strong></li>
                    </ul>
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/katoenen-tassen.html"
                       class="btn btn-success btn-xl">Katoenen tassen</a></div>
                <img src="https://www.pinkcube.nl/media/homepage/katoenen-tassen.png" title="Katoenen tassen bedrukken">
            </div>
            <div class="col-md-6 mhmr">
                <div class="head"><a href="https://www.pinkcube.nl/moeiteloos-het-mooiste-resultaat"
                                     title="Moeiteloos het mooiste resultaat" target="_blank">Moeiteloos het <strong>mooiste
                            resultaat</strong></a></div>
                <div class="row usp"><span class="usp-head">Gemakkelijk <strong>online bestellen</strong></span></div>
                <div class="row usp"><span class="usp-head"><strong>Gratis</strong> digitaal ontwerp</span></div>
                <div class="row usp"><span class="usp-head">Snelle levering en service</span></div>
            </div>
        </div>
    </div>
    <div class="row main-subcats">
        <div class="col-xs-12 col-md-6 col-lg-4">
            <div class="panel panel-default"><a href="https://www.pinkcube.nl/tassen-bedrukken/polyester-rugzakken.html"
                                                title="Polyester rugzakken bedrukken" class="panel-body">
                    <div class="cat-img"><img
                                src="https://www.pinkcube.nl/media/catalog/product/cache/9/small_image/275x/9df78eab33525d08d6e5fb8d27136e95/p/o/polyester-reclame-rugzakje-wit-deco.jpg"
                                alt="Polyester rugzakken bedrukken????" height="90"></div>
                    <div class="sub-info">
                        <div class="align-middle"><span class="name">Polyester rugzakken</span> <span
                                    class="sub-caption"> <ul> <li>Al vanaf 25 stuks</li> </ul> </span></div>
                    </div>
                </a></div>
        </div>
        <div class="col-xs-12 col-md-6 col-lg-4">
            <div class="panel panel-default"><a
                        href="https://www.pinkcube.nl/tassen-bedrukken/opvouwbare-boodschappentasjes.html"
                        title="Opvouwbare boodschappentasjes bedrukken" class="panel-body">
                    <div class="cat-img"><img
                                src="https://www.pinkcube.nl/media/catalog/product/cache/9/small_image/275x/9df78eab33525d08d6e5fb8d27136e95/o/p/opvouwbare-boodschappentas-met-unieke-opvouwfunctie-navy-532c-deco.png"
                                alt="Opvouwbare boodschappentasjes bedrukken????" height="90"></div>
                    <div class="sub-info">
                        <div class="align-middle"><span class="name">Opvouwbare boodschappentasjes</span> <span
                                    class="sub-caption"> <ul> <li>Al vanaf 25 stuks</li> </ul> </span></div>
                    </div>
                </a></div>
        </div>
        <div class="col-xs-12 col-md-6 col-lg-4">
            <div class="panel panel-default"><a href="https://www.pinkcube.nl/tassen-bedrukken/papieren-tassen.html"
                                                title="Papieren tassen bedrukken" class="panel-body">
                    <div class="cat-img"><img
                                src="https://www.pinkcube.nl/media/catalog/product/cache/9/small_image/275x/9df78eab33525d08d6e5fb8d27136e95/b/u/budget-papieren-tas-a4-deco.jpg"
                                alt="Papieren tassen bedrukken????" height="90"></div>
                    <div class="sub-info">
                        <div class="align-middle"><span class="name">Papieren tassen</span> <span class="sub-caption"> <ul> <li>Al vanaf 50 stuks</li> </ul> </span>
                        </div>
                    </div>
                </a></div>
        </div>
    </div>
</div>