<?php
/**
 * Product list template
 *
 * @var $block \SM\SumUp\Block\Post\RelatedProduct
 */

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$_helper = $block->getHelper();
$pos = $block->getPositioned();
$imageDisplayArea = 'category_page_list';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
$viewMode = 'grid';
$showDescription = true;

?>

<div class="product data items"
     data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0,"disabledState": "disabled"}}'>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-cars">Cars</a>
    </div>
    <div id="tab-cars" class="item content" data-role="content">
        <?php if (!$_productCollection->count()) : ?>
            <div class="message info empty">
                <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
            </div>
        <?php else : ?>
            <div class="hbr-main pad-main">
                <div class="block-title-main">
                    <div class="title-border"></div>
                </div>
                <div class="hbr-main">
                    <div style="margin: 0 -10px;">
                        <div class="hbr-content hbr-slider">
                            <?php foreach ($_productCollection as $_product) : ?>
                                <div class="hbr-inner">
                                    <div class=" hbr-inner item product product-item mp-blog-slider-item">
                                        <div class="product-item-info" data-container="product-<?= /* @noEscape */
                                        $viewMode ?>">
                                            <?php
                                            $productImage = $block->getImage($_product, $imageDisplayArea);
                                            if ($pos != null) {
                                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                    . 'top:' . $productImage->getHeight() . 'px;"';
                                            }
                                            ?>
                                            <?php // Product Image?>
                                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                               class="product photo product-item-photo"
                                               tabindex="-1">
                                                <?= $productImage->toHtml() ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <?php
                                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                                ?>
                                                <strong class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                                        <?= /* @noEscape */
                                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                                    </a>
                                                </strong>
                                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                                <?= /* @noEscape */
                                                $block->getProductPrice($_product) ?>
                                                <?= $block->getProductDetailsHtml($_product) ?>
                                                <!---->
                                                <div class="product-item-inner">
                                                    <div
                                                            class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                        <div
                                                                class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                            <?php if ($_product->isSaleable()) : ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>

                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                                      action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                                      method="post">
                                                                    <input type="hidden"
                                                                           name="product"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data']['product'] ?>">
                                                                    <input type="hidden" name="<?= /* @noEscape */
                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else : ?>
                                                                <?php if ($_product->isAvailable()) : ?>
                                                                    <div class="stock available">
                                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                    </div>
                                                                <?php else : ?>
                                                                    <div class="stock unavailable">
                                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div data-role="add-to-links"
                                                             class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                            <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                    <?php if ($showDescription) : ?>
                                                        <div class="product description product-item-description">
                                                            <?= /* @noEscape */
                                                            $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                                               title="<?= /* @noEscape */
                                                               $_productNameStripped ?>"
                                                               class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                                        </div>
                                                    <?php endif; ?>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?></div>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-movies">Movies</a>
    </div>
    <div id="tab-movies" class="item content" data-role="content">Movies content</div>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-movies1">Movies</a>
    </div>
    <div id="tab-movies11" class="item content" data-role="content">Movies content</div>



    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-music1">Music</a>
    </div>
    <div id="tab-music1" class="item content" data-role="content">123123123</div>
</div>
<div class="content related">
    <div class="main-subcats section">
        <div class="row theme-cat-group">
            <div class="col-xs-12">
                <div class="title">Populaire materialen</div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/katoenen-rugzakken.html" title="Katoenen rugzakken bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/katoenen-rugzakken.png" alt="Katoenen rugzakken bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Katoenen rugzakken</span>
                                <span class="sub-caption">
                        <ul>
                           <li>14 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/non-woven-rugzakken.html" title="Non woven rugzakken bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/non-woven-rugzakken.png" alt="Non woven rugzakken bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Non woven rugzakken</span>
                                <span class="sub-caption">
                        <ul>
                           <li>4 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/polyester-rugzakken.html" title="Polyester rugzakken bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/polyester-rugzakken.png" alt="Polyester rugzakken bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Polyester rugzakken</span>
                                <span class="sub-caption">
                        <ul>
                           <li>32 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/jute-tassen.html" title="Jute tassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/jute-tassen.png" alt="Jute tassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Jute tassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>39 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/non-woven-tassen.html" title="Non woven tassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/non-woven-tassen.png" alt="Non woven tassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Non woven tassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>43 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/vilten-tassen.html" title="Vilten tassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/vilten-tassen_1.png" alt="Vilten tassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Vilten tassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>5 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/non-woven-schoudertassen.html" title="Non woven schoudertassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/non-woven-schoudertassen_2.png" alt="Non woven schoudertassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Non woven schoudertassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>7 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row theme-cat-group">
            <div class="col-xs-12">
                <div class="title">Populaire categorieën</div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/luxe-rugzakken.html" title="Luxe rugzakken bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/luxe-rugzakken.png" alt="Luxe rugzakken bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Luxe rugzakken</span>
                                <span class="sub-caption">
                        <ul>
                           <li>85 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/eco-tassen.html" title="Eco tassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/eco-tassen.png" alt="Eco tassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Eco tassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>73 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/laptop-rugzakken-bedrukken.html" title="Laptop rugzakken bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/laptop-rugzakken_1.png" alt="Laptop rugzakken bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Laptop rugzakken</span>
                                <span class="sub-caption">
                        <ul>
                           <li>111 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/luxe-schoudertassen.html" title="Luxe schoudertassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/luxe-schoudertassen_1.png" alt="Luxe schoudertassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Luxe schoudertassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>28 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/alternatieven-plastic-tassen.html" title="Alternatieven plastic tassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/alternatieven-plastic-tassen.png" alt="Alternatieven plastic tassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Alternatieven plastic tassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>16 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/kinder-rugtas-bedrukken.html" title="Kinderrugzakken bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/kinderrugzakken_1.png" alt="Kinderrugzakken bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Kinderrugzakken</span>
                                <span class="sub-caption">
                        <ul>
                           <li>6 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row theme-cat-group">
            <div class="col-xs-12">
                <div class="title">Populaire soorten tassen</div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/draagtassen-bedrukken.html" title="Draagtassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/draagtassen.png" alt="Draagtassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Draagtassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>77 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/big-shoppers-bedrukken.html" title="Big Shoppers bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/big-shoppers_2.png" alt="Big Shoppers bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Big Shoppers</span>
                                <span class="sub-caption">
                        <ul>
                           <li>9 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/boodschappentassen-bedrukken.html" title="Boodschappentassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/boodschappentassen_1.png" alt="Boodschappentassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Boodschappentassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>56 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/documententassen.html" title="Documententassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/documententassen.png" alt="Documententassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Documententassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>25 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/goodiebags.html" title="Goodiebags bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/goodiebags.png" alt="Goodiebags bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Goodiebags</span>
                                <span class="sub-caption">
                        <ul>
                           <li>16 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/wijnflestassen.html" title="Wijnflestassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/wijnflestassen.png" alt="Wijnflestassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Wijnflestassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>4 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/koeltassen.html" title="Koeltassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/koeltassen.png" alt="Koeltassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Koeltassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>79 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/laptoptassen.html" title="Laptoptassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/laptoptassen_1.png" alt="Laptoptassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Laptoptassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>96 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/reistassen.html" title="Reistassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/reistassen_1.png" alt="Reistassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Reistassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>56 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/schoudertassen-bedrukken.html" title="Schoudertassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/schoudertassen_2.png" alt="Schoudertassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Schoudertassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>29 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/sporttassen.html" title="Sporttassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/sporttassen_1.png" alt="Sporttassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Sporttassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>51 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <div class="panel panel-default">
                    <a href="https://www.pinkcube.nl/tassen-bedrukken/strandtassen-bedrukken.html" title="Strandtassen bedrukken" class="panel-body">
                        <div class="cat-img">
                            <img src="https://www.pinkcube.nl/media/catalog/category/cache/117x90/strandtassen.png" alt="Strandtassen bedrukken" width="117" height="90">
                        </div>
                        <div class="sub-info">
                            <div class="align-middle">
                                <span class="name">Strandtassen</span>
                                <span class="sub-caption">
                        <ul>
                           <li>15 artikelen</li>
                        </ul>
                     </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" xml="space">// <![CDATA[
    require(['jquery', 'cpowlcarousel'], function ($) {
        jQuery(document).ready(function () {
            jQuery(".hbr-slider").owlCarousel({
                items: 4,
                itemsDesktop: [1080, 4],
                itemsDesktopSmall: [860, 3],
                itemsTablet: [768, 3],
                itemsTabletSmall: [639, 3],
                itemsMobile: [479, 2],
                pagination: false,
                navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                navigation: true,
            });
        });
    });
    // ]]></script>
