<div class="ad_content_banner">
    <div class="main-banner">
        <div class="main-category">
            <div class="text"><h2>Katoenen tassen bedrukken</h2>
                <ul>
                    <li>Al vanaf <strong>10</strong> stuks voor <strong>€ 45<span>,67</span></strong></li>
                    <li>Leverbaar binnen <strong><span class="delivery-days">4</span> werkdagen</strong></li>
                </ul>
                <a href="'.$url_base.'" class="btn btn-success btn-xl">Katoenen
                    tassen</a></div>
            <img src="https://www.pinkcube.nl/media/homepage/katoenen-tassen.png" title="Katoenen tassen bedrukken">
        </div>
        <div class="mhmr">

            <div class="head">
                <a href="'.$url_base.'"
                   title="Moeiteloos het mooiste resultaat" target="_blank">Moeiteloos het <strong>mooiste
                        resultaat</strong></a>
            </div>

            <div class=" usp">
                <i class="fa fa-check" aria-hidden="true"></i><span class="usp-head">Gemakkelijk <strong>online bestellen</strong></span>
            </div>

            <div class=" usp">
                <i class="fa fa-check" aria-hidden="true"></i> <span class="usp-head"><strong>Gratis</strong> digitaal ontwerp</span>
            </div>

            <div class=" usp">
                <i class="fa fa-check" aria-hidden="true"></i><span class="usp-head">Snelle levering en service</span>
            </div>

        </div>
    </div>
    <div class="main-subcat">
        <div class="ad_related_pro">
            <div class="raleted_pro_general">
                <div class="raleted_pro_detailds"><a
                        href=""
                        title="Polyester rugzakken bedrukken" class="panel-body">
                        <div class="cat-img"><img
                                src="https://www.pinkcube.nl/media/catalog/product/cache/9/small_image/275x/9df78eab33525d08d6e5fb8d27136e95/p/o/polyester-reclame-rugzakje-wit-deco.jpg"
                                alt="Polyester rugzakken bedrukken" height="90"></div>
                        <div class="sub-info">
                            <div class="align-middle"><span class="name">Polyester rugzakken</span> <span
                                    class="sub-caption"> <ul> <li>Al vanaf 25 stuks</li> </ul> </span></div>
                        </div>
                        <i class="fa fa-angle-rights" aria-hidden="true"></i>
                    </a>
                </div>
                <div class="raleted_pro_detailds"><a
                        href=""
                        title="Opvouwbare boodschappentasjes bedrukken" class="panel-body">
                        <div class="cat-img"><img
                                src="https://www.pinkcube.nl/media/catalog/product/cache/9/small_image/275x/9df78eab33525d08d6e5fb8d27136e95/o/p/opvouwbare-boodschappentas-met-unieke-opvouwfunctie-navy-532c-deco.png"
                                alt="Opvouwbare boodschappentasjes bedrukken????" height="90"></div>
                        <div class="sub-info">
                            <div class="align-middle"><span class="name">Opvouwbare boodschappentasjes</span> <span
                                    class="sub-caption"> <ul> <li>Al vanaf 25 stuks</li> </ul> </span></div>
                        </div>
                        <i class="fa fa-angle-rights" aria-hidden="true"></i>
                    </a>
                </div>
                <div class="raleted_pro_detailds"><a
                        href=""
                        title="Papieren tassen bedrukken????" class="panel-body">
                        <div class="cat-img"><img
                                src="https://www.pinkcube.nl/media/catalog/product/cache/9/small_image/275x/9df78eab33525d08d6e5fb8d27136e95/b/u/budget-papieren-tas-a4-deco.jpg"
                                alt="Papieren tassen bedrukken????" height="90"></div>
                        <div class="sub-info">
                            <div class="align-middle"><span class="name">Papieren tassen</span> <span
                                    class="sub-caption"> <ul> <li>Al vanaf 50 stuks</li> </ul> </span></div>
                        </div>

                    </a>
                    <i class="fa fa-angle-rights" aria-hidden="true"></i>
                </div>
            </div>
        </div>
    </div>

</div>
