<div data-bind="scope: 'Orderattachment'">
        <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "Orderattachment": {
                            "component": "Ecentura_Orderattachment/js/attachment",
                             "dataconfig": <?= $this->getAttachmentConfig() ?>
                        }
                    }
                }
            }
        }
</script>